package es.yahoousefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.yahoousefulearnings.engine.Field;
import es.yahoousefulearnings.engine.LongFormatField;
/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=balanceSheetHistory"
 * key to find in jackson: balanceSheetStatements
 *
 * BalanceSheetStatement will have list of objects will be called balanceSheetStatements
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BalanceSheetStatement extends CompanyData {
  
  @JsonProperty("endDate")
  private Field endDate;
  @JsonProperty("cash")
  private LongFormatField cash;
  @JsonProperty("shortTermInvestments")
  private LongFormatField shortTermInvestments;
  @JsonProperty("netReceivables")
  private LongFormatField netReceivables;
  @JsonProperty("inventory")
  private LongFormatField inventory;
  @JsonProperty("otherCurrentAssets")
  private LongFormatField otherCurrentAssets;
  @JsonProperty("totalCurrentAssets")
  private LongFormatField totalCurrentAssets;
  @JsonProperty("longTermInvestments")
  private LongFormatField longTermInvestments;
  @JsonProperty("propertyPlantEquipment")
  private LongFormatField propertyPlantEquipment;
  @JsonProperty("goodWill")
  private LongFormatField goodWill;
  @JsonProperty("intangibleAssets")
  private LongFormatField intangibleAssets;
  @JsonProperty("otherAssets")
  private LongFormatField otherAssets;
  @JsonProperty("totalAssets")
  private LongFormatField totalAssets;
  @JsonProperty("accountsPayable")
  private LongFormatField accountsPayable;
  @JsonProperty("shortLongTermDebt")
  private LongFormatField shortLongTermDebt;
  @JsonProperty("otherCurrentLiab")
  private LongFormatField otherCurrentLiab;
  @JsonProperty("longTermDebt")
  private LongFormatField longTermDebt;
  @JsonProperty("otherLiab")
  private LongFormatField otherLiab;
  @JsonProperty("deferredLongTermLiab")
  private LongFormatField deferredLongTermLiab;
  @JsonProperty("totalCurrentLiabilities")
  private LongFormatField totalCurrentLiabilities;
  @JsonProperty("totalLiab")
  private LongFormatField totalLiab;
  @JsonProperty("commonStock")
  private LongFormatField commonStock;
  @JsonProperty("retainedEarnings")
  private LongFormatField retainedEarnings;
  @JsonProperty("otherStockholderEquity")
  private LongFormatField otherStockholderEquity;
  @JsonProperty("totalStockholderEquity")
  private LongFormatField totalStockholderEquity;
  @JsonProperty("netTangibleAssets")
  private LongFormatField netTangibleAssets; 

  public Field getEndDate() {
    return endDate;
  }

  public void setEndDate(Field endDate) {
    this.endDate = endDate;
  }

  public LongFormatField getCash() {
    return cash;
  }

  public void setCash(LongFormatField cash) {
    this.cash = cash;
  }

  public LongFormatField getShortTermInvestments() {
    return shortTermInvestments;
  }

  public void setShortTermInvestments(LongFormatField shortTermInvestments) {
    this.shortTermInvestments = shortTermInvestments;
  }

  public LongFormatField getNetReceivables() {
    return netReceivables;
  }

  public void setNetReceivables(LongFormatField netReceivables) {
    this.netReceivables = netReceivables;
  }

  public LongFormatField getInventory() {
    return inventory;
  }

  public void setInventory(LongFormatField inventory) {
    this.inventory = inventory;
  }

  public LongFormatField getOtherCurrentAssets() {
    return otherCurrentAssets;
  }

  public void setOtherCurrentAssets(LongFormatField otherCurrentAssets) {
    this.otherCurrentAssets = otherCurrentAssets;
  }

  public LongFormatField getTotalCurrentAssets() {
    return totalCurrentAssets;
  }

  public void setTotalCurrentAssets(LongFormatField totalCurrentAssets) {
    this.totalCurrentAssets = totalCurrentAssets;
  }

  public LongFormatField getLongTermInvestments() {
    return longTermInvestments;
  }

  public void setLongTermInvestments(LongFormatField longTermInvestments) {
    this.longTermInvestments = longTermInvestments;
  }

  public LongFormatField getPropertyPlantEquipment() {
    return propertyPlantEquipment;
  }

  public void setPropertyPlantEquipment(LongFormatField propertyPlantEquipment) {
    this.propertyPlantEquipment = propertyPlantEquipment;
  }

  public LongFormatField getGoodWill() {
    return goodWill;
  }

  public void setGoodWill(LongFormatField goodWill) {
    this.goodWill = goodWill;
  }

  public LongFormatField getIntangibleAssets() {
    return intangibleAssets;
  }

  public void setIntangibleAssets(LongFormatField intangibleAssets) {
    this.intangibleAssets = intangibleAssets;
  }

  public LongFormatField getOtherAssets() {
    return otherAssets;
  }

  public void setOtherAssets(LongFormatField otherAssets) {
    this.otherAssets = otherAssets;
  }

  public LongFormatField getTotalAssets() {
    return totalAssets;
  }

  public void setTotalAssets(LongFormatField totalAssets) {
    this.totalAssets = totalAssets;
  }

  public LongFormatField getAccountsPayable() {
    return accountsPayable;
  }

  public void setAccountsPayable(LongFormatField accountsPayable) {
    this.accountsPayable = accountsPayable;
  }

  public LongFormatField getShortLongTermDebt() {
    return shortLongTermDebt;
  }

  public void setShortLongTermDebt(LongFormatField shortLongTermDebt) {
    this.shortLongTermDebt = shortLongTermDebt;
  }

  public LongFormatField getOtherCurrentLiab() {
    return otherCurrentLiab;
  }

  public void setOtherCurrentLiab(LongFormatField otherCurrentLiab) {
    this.otherCurrentLiab = otherCurrentLiab;
  }

  public LongFormatField getLongTermDebt() {
    return longTermDebt;
  }

  public void setLongTermDebt(LongFormatField longTermDebt) {
    this.longTermDebt = longTermDebt;
  }

  public LongFormatField getOtherLiab() {
    return otherLiab;
  }

  public void setOtherLiab(LongFormatField otherLiab) {
    this.otherLiab = otherLiab;
  }

  public LongFormatField getDeferredLongTermLiab() {
    return deferredLongTermLiab;
  }

  public void setDeferredLongTermLiab(LongFormatField deferredLongTermLiab) {
    this.deferredLongTermLiab = deferredLongTermLiab;
  }

  public LongFormatField getTotalCurrentLiabilities() {
    return totalCurrentLiabilities;
  }

  public void setTotalCurrentLiabilities(LongFormatField totalCurrentLiabilities) {
    this.totalCurrentLiabilities = totalCurrentLiabilities;
  }

  public LongFormatField getTotalLiab() {
    return totalLiab;
  }

  public void setTotalLiab(LongFormatField totalLiab) {
    this.totalLiab = totalLiab;
  }

  public LongFormatField getCommonStock() {
    return commonStock;
  }

  public void setCommonStock(LongFormatField commonStock) {
    this.commonStock = commonStock;
  }

  public LongFormatField getRetainedEarnings() {
    return retainedEarnings;
  }

  public void setRetainedEarnings(LongFormatField retainedEarnings) {
    this.retainedEarnings = retainedEarnings;
  }

  public LongFormatField getOtherStockholderEquity() {
    return otherStockholderEquity;
  }

  public void setOtherStockholderEquity(LongFormatField otherStockholderEquity) {
    this.otherStockholderEquity = otherStockholderEquity;
  }

  public LongFormatField getTotalStockholderEquity() {
    return totalStockholderEquity;
  }

  public void setTotalStockholderEquity(LongFormatField totalStockholderEquity) {
    this.totalStockholderEquity = totalStockholderEquity;
  }

  public LongFormatField getNetTangibleAssets() {
    return netTangibleAssets;
  }

  public void setNetTangibleAssets(LongFormatField netTangibleAssets) {
    this.netTangibleAssets = netTangibleAssets;
  }
}
