package es.yahoousefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.yahoousefulearnings.engine.Field;
import es.yahoousefulearnings.engine.LongFormatField;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=defaultKeyStatistics"
 * key to find in jackson: defaultKeyStatistics
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class DefaultKeyStatistics {

  @JsonProperty("lastSplitFactor")
  private String lastSplitFactor; // "7/1",

  @JsonProperty("forwardPE")
  private Field forwardPE; // {Field},
  @JsonProperty("profitMargins")
  private Field profitMargins; // {Field},
  @JsonProperty("heldPercentInsiders")
  private Field heldPercentInsiders; // { Field},
  @JsonProperty("heldPercentInstitutions")
  private Field heldPercentInstitutions; // { Field},
  @JsonProperty("shortRatio")
  private Field shortRatio; // { Field},
  @JsonProperty("shortPercentOfFloat")
  private Field shortPercentOfFloat; // { Field},
  @JsonProperty("beta")
  private Field beta; // { Field},
  @JsonProperty("bookValue")
  private Field bookValue; // { Field},
  @JsonProperty("priceToBook")
  private Field priceToBook; // { Field},
  @JsonProperty("lastFiscalYearEnd")
  private Field lastFiscalYearEnd; // { Field},
  @JsonProperty("nextFiscalYearEnd")
  private Field nextFiscalYearEnd; // { Field},
  @JsonProperty("mostRecentQuarter")
  private Field mostRecentQuarter; // { Field},
  @JsonProperty("earningsQuarterlyGrowth")
  private Field earningsQuarterlyGrowth; // {Field},
  @JsonProperty("trailingEps")
  private Field trailingEps; // { Field},
  @JsonProperty("forwardEps")
  private Field forwardEps; // { Field},
  @JsonProperty("pegRatio")
  private Field pegRatio; // { Field},
  @JsonProperty("lastSplitDate")
  private Field lastSplitDate; // { Field},
  @JsonProperty("enterpriseToRevenue")
  private Field enterpriseToRevenue; // { Field},
  @JsonProperty("enterpriseToEbitda")
  private Field enterpriseToEbitda; // { Field},
  @JsonProperty("SandP52WeekChange")
  private Field sandP52WeekChange; // { Field},

  @JsonProperty("floatShares")
  private LongFormatField floatShares; // {LongFormatField},
  @JsonProperty("sharesOutstanding")
  private LongFormatField sharesOutstanding; // {LongFormatField},
  @JsonProperty("sharesShort")
  private LongFormatField sharesShort; // {LongFormatField},
  @JsonProperty("sharesShortPriorMonth")
  private LongFormatField sharesShortPriorMonth; // {LongFormatField},
  @JsonProperty("netIncomeToCommon")
  private LongFormatField netIncomeToCommon; // { LongFormatField },
  @JsonProperty("enterpriseValue")
  private LongFormatField enterpriseValue; // {LongFormatField},

  public String getLastSplitFactor() {
    return lastSplitFactor;
  }

  public void setLastSplitFactor(String lastSplitFactor) {
    this.lastSplitFactor = lastSplitFactor;
  }

  public Field getForwardPE() {
    return forwardPE;
  }

  public void setForwardPE(Field forwardPE) {
    this.forwardPE = forwardPE;
  }

  public Field getProfitMargins() {
    return profitMargins;
  }

  public void setProfitMargins(Field profitMargins) {
    this.profitMargins = profitMargins;
  }

  public Field getHeldPercentInsiders() {
    return heldPercentInsiders;
  }

  public void setHeldPercentInsiders(Field heldPercentInsiders) {
    this.heldPercentInsiders = heldPercentInsiders;
  }

  public Field getHeldPercentInstitutions() {
    return heldPercentInstitutions;
  }

  public void setHeldPercentInstitutions(Field heldPercentInstitutions) {
    this.heldPercentInstitutions = heldPercentInstitutions;
  }

  public Field getShortRatio() {
    return shortRatio;
  }

  public void setShortRatio(Field shortRatio) {
    this.shortRatio = shortRatio;
  }

  public Field getShortPercentOfFloat() {
    return shortPercentOfFloat;
  }

  public void setShortPercentOfFloat(Field shortPercentOfFloat) {
    this.shortPercentOfFloat = shortPercentOfFloat;
  }

  public Field getBeta() {
    return beta;
  }

  public void setBeta(Field beta) {
    this.beta = beta;
  }

  public Field getBookValue() {
    return bookValue;
  }

  public void setBookValue(Field bookValue) {
    this.bookValue = bookValue;
  }

  public Field getPriceToBook() {
    return priceToBook;
  }

  public void setPriceToBook(Field priceToBook) {
    this.priceToBook = priceToBook;
  }

  public Field getLastFiscalYearEnd() {
    return lastFiscalYearEnd;
  }

  public void setLastFiscalYearEnd(Field lastFiscalYearEnd) {
    this.lastFiscalYearEnd = lastFiscalYearEnd;
  }

  public Field getNextFiscalYearEnd() {
    return nextFiscalYearEnd;
  }

  public void setNextFiscalYearEnd(Field nextFiscalYearEnd) {
    this.nextFiscalYearEnd = nextFiscalYearEnd;
  }

  public Field getMostRecentQuarter() {
    return mostRecentQuarter;
  }

  public void setMostRecentQuarter(Field mostRecentQuarter) {
    this.mostRecentQuarter = mostRecentQuarter;
  }

  public Field getEarningsQuarterlyGrowth() {
    return earningsQuarterlyGrowth;
  }

  public void setEarningsQuarterlyGrowth(Field earningsQuarterlyGrowth) {
    this.earningsQuarterlyGrowth = earningsQuarterlyGrowth;
  }

  public Field getTrailingEps() {
    return trailingEps;
  }

  public void setTrailingEps(Field trailingEps) {
    this.trailingEps = trailingEps;
  }

  public Field getForwardEps() {
    return forwardEps;
  }

  public void setForwardEps(Field forwardEps) {
    this.forwardEps = forwardEps;
  }

  public Field getPegRatio() {
    return pegRatio;
  }

  public void setPegRatio(Field pegRatio) {
    this.pegRatio = pegRatio;
  }

  public Field getLastSplitDate() {
    return lastSplitDate;
  }

  public void setLastSplitDate(Field lastSplitDate) {
    this.lastSplitDate = lastSplitDate;
  }

  public Field getEnterpriseToRevenue() {
    return enterpriseToRevenue;
  }

  public void setEnterpriseToRevenue(Field enterpriseToRevenue) {
    this.enterpriseToRevenue = enterpriseToRevenue;
  }

  public Field getEnterpriseToEbitda() {
    return enterpriseToEbitda;
  }

  public void setEnterpriseToEbitda(Field enterpriseToEbitda) {
    this.enterpriseToEbitda = enterpriseToEbitda;
  }

  public Field getSandP52WeekChange() {
    return sandP52WeekChange;
  }

  public void setSandP52WeekChange(Field sandP52WeekChange) {
    this.sandP52WeekChange = sandP52WeekChange;
  }

  public LongFormatField getFloatShares() {
    return floatShares;
  }

  public void setFloatShares(LongFormatField floatShares) {
    this.floatShares = floatShares;
  }

  public LongFormatField getSharesOutstanding() {
    return sharesOutstanding;
  }

  public void setSharesOutstanding(LongFormatField sharesOutstanding) {
    this.sharesOutstanding = sharesOutstanding;
  }

  public LongFormatField getSharesShort() {
    return sharesShort;
  }

  public void setSharesShort(LongFormatField sharesShort) {
    this.sharesShort = sharesShort;
  }

  public LongFormatField getSharesShortPriorMonth() {
    return sharesShortPriorMonth;
  }

  public void setSharesShortPriorMonth(LongFormatField sharesShortPriorMonth) {
    this.sharesShortPriorMonth = sharesShortPriorMonth;
  }

  public LongFormatField getNetIncomeToCommon() {
    return netIncomeToCommon;
  }

  public void setNetIncomeToCommon(LongFormatField netIncomeToCommon) {
    this.netIncomeToCommon = netIncomeToCommon;
  }

  public LongFormatField getEnterpriseValue() {
    return enterpriseValue;
  }

  public void setEnterpriseValue(LongFormatField enterpriseValue) {
    this.enterpriseValue = enterpriseValue;
  }



  /*
  * *** NULL DATA ***
  @JsonProperty("revenueQuarterlyGrowth")
  private Field revenueQuarterlyGrowth; // {},
  @JsonProperty("morningStarOverallRating")
  private Field morningStarOverallRating; // {},
  @JsonProperty("morningStarRiskRating")
  private Field morningStarRiskRating; // {},
  @JsonProperty("category")
  private Field category; // null,
  @JsonProperty("annualReportExpenseRatio")
  private Field annualReportExpenseRatio; // {},
  @JsonProperty("ytdReturn")
  private Field ytdReturn; // {},
  @JsonProperty("beta3Year")
  private Field beta3Year; // {},
  @JsonProperty("totalAssets")
  private Field totalAssets; // {},
  @JsonProperty("yield")
  private Field yield; // {},
  @JsonProperty("fundFamily")
  private Field fundFamily; // null,
  @JsonProperty("fundInceptionDate")
  private Field fundInceptionDate; // {},
  @JsonProperty("legalType")
  private Field legalType; // null,
  @JsonProperty("threeYearAverageReturn")
  private Field threeYearAverageReturn; // {},
  @JsonProperty("fiveYearAverageReturn")
  private Field fiveYearAverageReturn; // {},
  @JsonProperty("priceToSalesTrailing12Months")
  private Field priceToSalesTrailing12Months; // {},
  @JsonProperty("lastDividendValue")
  private Field lastDividendValue; // {},
  @JsonProperty("lastCapGain")
  private Field lastCapGain; // {},
  @JsonProperty("annualHoldingsTurnover")
  private Field annualHoldingsTurnover; // {}
   */

}
