package es.yahoousefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.yahoousefulearnings.engine.Field;
import es.yahoousefulearnings.engine.LongFormatField;
/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=financialData"
 * key to find in jackson: financialData
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class FinancialData {

  @JsonProperty("currentPrice")
  private Field currentPrice;
  @JsonProperty("targetHighPrice")
  private Field targetHighPrice;
  @JsonProperty("targetLowPrice")
  private Field targetLowPrice;
  @JsonProperty("targetMeanPrice")
  private Field targetMeanPrice;
  @JsonProperty("targetMedianPrice")
  private Field targetMedianPrice;
  @JsonProperty("recommendationMean")
  private Field recommendationMean;
  @JsonProperty("recommendationKey")
  private String recommendationKey;
  @JsonProperty("totalCashPerShare")
  private Field totalCashPerShare;
  @JsonProperty("quickRatio")
  private Field quickRatio;
  @JsonProperty("currentRatio")
  private Field currentRatio;
  @JsonProperty("returnOnAssets")
  private Field returnOnAssets;
  @JsonProperty("returnOnEquity")
  private Field returnOnEquity;
  @JsonProperty("earningsGrowth")
  private Field earningsGrowth;
  @JsonProperty("revenueGrowth")
  private Field revenueGrowth;
  @JsonProperty("grossMargins")
  private Field grossMargins;
  @JsonProperty("ebitdaMargins")
  private Field ebitdaMargins;
  @JsonProperty("operatingMargins")
  private Field operatingMargins;
  @JsonProperty("profitMargins")
  private Field profitMargins;

  @JsonProperty("numberOfAnalystOpinions")
  private LongFormatField numberOfAnalystOpinions;
  @JsonProperty("totalCash")
  private LongFormatField totalCash;
  @JsonProperty("ebitda")
  private LongFormatField ebitda;
  @JsonProperty("totalDebt")
  private LongFormatField totalDebt;
  @JsonProperty("totalRevenue")
  private LongFormatField totalRevenue;
  @JsonProperty("debtToEquity")
  private LongFormatField debtToEquity;
  @JsonProperty("grossProfits")
  private LongFormatField grossProfits;
  @JsonProperty("freeCashflow")
  private LongFormatField freeCashflow;
  @JsonProperty("operatingCashflow")
  private LongFormatField operatingCashflow;


  public Field getCurrentPrice() {
    return currentPrice;
  }

  public void setCurrentPrice(Field currentPrice) {
    this.currentPrice = currentPrice;
  }

  public Field getTargetHighPrice() {
    return targetHighPrice;
  }

  public void setTargetHighPrice(Field targetHighPrice) {
    this.targetHighPrice = targetHighPrice;
  }

  public Field getTargetLowPrice() {
    return targetLowPrice;
  }

  public void setTargetLowPrice(Field targetLowPrice) {
    this.targetLowPrice = targetLowPrice;
  }

  public Field getTargetMeanPrice() {
    return targetMeanPrice;
  }

  public void setTargetMeanPrice(Field targetMeanPrice) {
    this.targetMeanPrice = targetMeanPrice;
  }

  public Field getTargetMedianPrice() {
    return targetMedianPrice;
  }

  public void setTargetMedianPrice(Field targetMedianPrice) {
    this.targetMedianPrice = targetMedianPrice;
  }

  public Field getRecommendationMean() {
    return recommendationMean;
  }

  public void setRecommendationMean(Field recommendationMean) {
    this.recommendationMean = recommendationMean;
  }

  public String getRecommendationKey() {
    return recommendationKey;
  }

  public void setRecommendationKey(String recommendationKey) {
    this.recommendationKey = recommendationKey;
  }

  public Field getTotalCashPerShare() {
    return totalCashPerShare;
  }

  public void setTotalCashPerShare(Field totalCashPerShare) {
    this.totalCashPerShare = totalCashPerShare;
  }

  public Field getQuickRatio() {
    return quickRatio;
  }

  public void setQuickRatio(Field quickRatio) {
    this.quickRatio = quickRatio;
  }

  public Field getCurrentRatio() {
    return currentRatio;
  }

  public void setCurrentRatio(Field currentRatio) {
    this.currentRatio = currentRatio;
  }

  public Field getReturnOnAssets() {
    return returnOnAssets;
  }

  public void setReturnOnAssets(Field returnOnAssets) {
    this.returnOnAssets = returnOnAssets;
  }

  public Field getReturnOnEquity() {
    return returnOnEquity;
  }

  public void setReturnOnEquity(Field returnOnEquity) {
    this.returnOnEquity = returnOnEquity;
  }

  public Field getEarningsGrowth() {
    return earningsGrowth;
  }

  public void setEarningsGrowth(Field earningsGrowth) {
    this.earningsGrowth = earningsGrowth;
  }

  public Field getRevenueGrowth() {
    return revenueGrowth;
  }

  public void setRevenueGrowth(Field revenueGrowth) {
    this.revenueGrowth = revenueGrowth;
  }

  public Field getGrossMargins() {
    return grossMargins;
  }

  public void setGrossMargins(Field grossMargins) {
    this.grossMargins = grossMargins;
  }

  public Field getEbitdaMargins() {
    return ebitdaMargins;
  }

  public void setEbitdaMargins(Field ebitdaMargins) {
    this.ebitdaMargins = ebitdaMargins;
  }

  public Field getOperatingMargins() {
    return operatingMargins;
  }

  public void setOperatingMargins(Field operatingMargins) {
    this.operatingMargins = operatingMargins;
  }

  public Field getProfitMargins() {
    return profitMargins;
  }

  public void setProfitMargins(Field profitMargins) {
    this.profitMargins = profitMargins;
  }

  public LongFormatField getNumberOfAnalystOpinions() {
    return numberOfAnalystOpinions;
  }

  public void setNumberOfAnalystOpinions(LongFormatField numberOfAnalystOpinions) {
    this.numberOfAnalystOpinions = numberOfAnalystOpinions;
  }

  public LongFormatField getTotalCash() {
    return totalCash;
  }

  public void setTotalCash(LongFormatField totalCash) {
    this.totalCash = totalCash;
  }

  public LongFormatField getEbitda() {
    return ebitda;
  }

  public void setEbitda(LongFormatField ebitda) {
    this.ebitda = ebitda;
  }

  public LongFormatField getTotalDebt() {
    return totalDebt;
  }

  public void setTotalDebt(LongFormatField totalDebt) {
    this.totalDebt = totalDebt;
  }

  public LongFormatField getTotalRevenue() {
    return totalRevenue;
  }

  public void setTotalRevenue(LongFormatField totalRevenue) {
    this.totalRevenue = totalRevenue;
  }

  public LongFormatField getDebtToEquity() {
    return debtToEquity;
  }

  public void setDebtToEquity(LongFormatField debtToEquity) {
    this.debtToEquity = debtToEquity;
  }

  public LongFormatField getGrossProfits() {
    return grossProfits;
  }

  public void setGrossProfits(LongFormatField grossProfits) {
    this.grossProfits = grossProfits;
  }

  public LongFormatField getFreeCashflow() {
    return freeCashflow;
  }

  public void setFreeCashflow(LongFormatField freeCashflow) {
    this.freeCashflow = freeCashflow;
  }

  public LongFormatField getOperatingCashflow() {
    return operatingCashflow;
  }

  public void setOperatingCashflow(LongFormatField operatingCashflow) {
    this.operatingCashflow = operatingCashflow;
  }
}