package es.usefulearnings.entities.option;

import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query1.finance.yahoo.com/v10/finance/quoteSummary/OPTION_SYMBOL?modules=price"
 * key to find in jackson: price
 *
 * @author Yago Rodríguez
 */
public class Price extends OptionData implements Serializable {
  @JsonProperty("exchange")
  @EntityParameter(name = "Exchange", parameterType = ParameterType.RAW_STRING)
  private String exchange; // "OPR",

  @JsonProperty("exchangeName")
  @EntityParameter(name = "Exchange name", parameterType = ParameterType.RAW_STRING)
  private String exchangeName; // "OPR",

  @JsonProperty("marketState")
  @EntityParameter(name = "Market state", parameterType = ParameterType.RAW_STRING)
  private String marketState; // "REGULAR",

  @JsonProperty("quoteType")
  @EntityParameter(name = "Quote type", parameterType = ParameterType.RAW_STRING)
  private String quoteType; // "OPTION",

  @JsonProperty("symbol")
  @EntityParameter(name = "Symbol", parameterType = ParameterType.RAW_STRING)
  private String symbol; // "AAPL160812C00070000",

  @JsonProperty("underlyingSymbol")
  @EntityParameter(name = "Company's symbol", parameterType = ParameterType.RAW_STRING)
  private String underlyingSymbol; // "AAPL",

  @JsonProperty("currency")
  @EntityParameter(name = "Currency", parameterType = ParameterType.RAW_STRING)
  private String currency; // "USD",

  @JsonProperty("currencySymbol")
  @EntityParameter(name = "Currency symbol", parameterType = ParameterType.RAW_STRING)
  private String currencySymbol; // "$"

  @JsonProperty("regularMarketChangePercent")
  @EntityParameter(name = "Regular market change percent", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketChangePercent;

  @JsonProperty("regularMarketChange")
  @EntityParameter(name = "Regular market change", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketChange;

  @JsonProperty("regularMarketTime")
  @EntityParameter(name = "Regular market time", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField regularMarketTime; // 1470439901,

  @JsonProperty("regularMarketPrice")
  @EntityParameter(name = "Regular market price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketPrice;

  @JsonProperty("regularMarketDayHigh")
  @EntityParameter(name = "Regular market day high", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketDayHigh;

  @JsonProperty("regularMarketDayLow")
  @EntityParameter(name = "Regular market day low", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketDayLow;

  @JsonProperty("regularMarketVolume")
  @EntityParameter(name = "Regular market volume", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooLongFormatField regularMarketVolume;

  @JsonProperty("regularMarketPreviousClose")
  @EntityParameter(name = "Regular market previous close", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketPreviousClose;

  @JsonProperty("regularMarketSource")
  @EntityParameter(name = "Regular market source", parameterType = ParameterType.RAW_STRING)
  private YahooField regularMarketSource; // "DELAYED",

  @JsonProperty("regularMarketOpen")
  @EntityParameter(name = "regular market open", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField regularMarketOpen;

  @JsonProperty("strikePrice")
  @EntityParameter(name = "Strike price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField strikePrice;

  @JsonProperty("openInterest")
  @EntityParameter(name = "Open interest", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooLongFormatField openInterest;

  @JsonProperty("expireDate")
  @EntityParameter(name = "Expiration date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField expireDate;

  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public String getExchangeName() {
    return exchangeName;
  }

  public void setExchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
  }

  public String getMarketState() {
    return marketState;
  }

  public void setMarketState(String marketState) {
    this.marketState = marketState;
  }

  public String getQuoteType() {
    return quoteType;
  }

  public void setQuoteType(String quoteType) {
    this.quoteType = quoteType;
  }

  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }

  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public String getCurrencySymbol() {
    return currencySymbol;
  }

  public void setCurrencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  public YahooField getRegularMarketChangePercent() {
    return regularMarketChangePercent;
  }

  public void setRegularMarketChangePercent(YahooField regularMarketChangePercent) {
    this.regularMarketChangePercent = regularMarketChangePercent;
  }

  public YahooField getRegularMarketChange() {
    return regularMarketChange;
  }

  public void setRegularMarketChange(YahooField regularMarketChange) {
    this.regularMarketChange = regularMarketChange;
  }

  public YahooField getRegularMarketTime() {
    return regularMarketTime;
  }

  public void setRegularMarketTime(YahooField regularMarketTime) {
    this.regularMarketTime = regularMarketTime;
  }

  public YahooField getRegularMarketPrice() {
    return regularMarketPrice;
  }

  public void setRegularMarketPrice(YahooField regularMarketPrice) {
    this.regularMarketPrice = regularMarketPrice;
  }

  public YahooField getRegularMarketDayHigh() {
    return regularMarketDayHigh;
  }

  public void setRegularMarketDayHigh(YahooField regularMarketDayHigh) {
    this.regularMarketDayHigh = regularMarketDayHigh;
  }

  public YahooField getRegularMarketDayLow() {
    return regularMarketDayLow;
  }

  public void setRegularMarketDayLow(YahooField regularMarketDayLow) {
    this.regularMarketDayLow = regularMarketDayLow;
  }

  public YahooLongFormatField getRegularMarketVolume() {
    return regularMarketVolume;
  }

  public void setRegularMarketVolume(YahooLongFormatField regularMarketVolume) {
    this.regularMarketVolume = regularMarketVolume;
  }

  public YahooField getRegularMarketPreviousClose() {
    return regularMarketPreviousClose;
  }

  public void setRegularMarketPreviousClose(YahooField regularMarketPreviousClose) {
    this.regularMarketPreviousClose = regularMarketPreviousClose;
  }

  public YahooField getRegularMarketSource() {
    return regularMarketSource;
  }

  public void setRegularMarketSource(YahooField regularMarketSource) {
    this.regularMarketSource = regularMarketSource;
  }

  public YahooField getRegularMarketOpen() {
    return regularMarketOpen;
  }

  public void setRegularMarketOpen(YahooField regularMarketOpen) {
    this.regularMarketOpen = regularMarketOpen;
  }

  public YahooField getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(YahooField strikePrice) {
    this.strikePrice = strikePrice;
  }

  public YahooLongFormatField getOpenInterest() {
    return openInterest;
  }

  public void setOpenInterest(YahooLongFormatField openInterest) {
    this.openInterest = openInterest;
  }

  public YahooField getExpireDate() {
    return expireDate;
  }

  public void setExpireDate(YahooField expireDate) {
    this.expireDate = expireDate;
  }
}
