package es.usefulearnings.entities.option;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query1.finance.yahoo.com/v10/finance/quoteSummary/OPTION_SYMBOL?modules=summaryDetail"
 * key to find in jackson: summaryDetail
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SummaryDetail extends OptionData implements Serializable {
  @JsonProperty("previousClose")
  private YahooField previousClose;
  @JsonProperty("open")
  private YahooField open;
  @JsonProperty("dayLow")
  private YahooField dayLow;
  @JsonProperty("dayHigh")
  private YahooField dayHigh;
  @JsonProperty("regularMarketPreviousClose")
  private YahooField regularMarketPreviousClose;
  @JsonProperty("regularMarketOpen")
  private YahooField regularMarketOpen;
  @JsonProperty("regularMarketDayLow")
  private YahooField regularMarketDayLow;
  @JsonProperty("regularMarketDayHigh")
  private YahooField regularMarketDayHigh;
  @JsonProperty("bid")
  private YahooField bid;
  @JsonProperty("ask")
  private YahooField ask;
  @JsonProperty("expireDate")
  private YahooField expireDate;
  @JsonProperty("strikePrice")
  private YahooField strikePrice;
  @JsonProperty("fiftyTwoWeekLow")
  private YahooField fiftyTwoWeekLow;
  @JsonProperty("fiftyTwoWeekHigh")
  private YahooField fiftyTwoWeekHigh;
  @JsonProperty("openInterest")
  private YahooLongFormatField openInterest;
  @JsonProperty("volume")
  private YahooLongFormatField volume;
  @JsonProperty("regularMarketVolume")
  private YahooLongFormatField regularMarketVolume;

  public YahooField getPreviousClose() {
    return previousClose;
  }

  public void setPreviousClose(YahooField previousClose) {
    this.previousClose = previousClose;
  }

  public YahooField getOpen() {
    return open;
  }

  public void setOpen(YahooField open) {
    this.open = open;
  }

  public YahooField getDayLow() {
    return dayLow;
  }

  public void setDayLow(YahooField dayLow) {
    this.dayLow = dayLow;
  }

  public YahooField getDayHigh() {
    return dayHigh;
  }

  public void setDayHigh(YahooField dayHigh) {
    this.dayHigh = dayHigh;
  }

  public YahooField getRegularMarketPreviousClose() {
    return regularMarketPreviousClose;
  }

  public void setRegularMarketPreviousClose(YahooField regularMarketPreviousClose) {
    this.regularMarketPreviousClose = regularMarketPreviousClose;
  }

  public YahooField getRegularMarketOpen() {
    return regularMarketOpen;
  }

  public void setRegularMarketOpen(YahooField regularMarketOpen) {
    this.regularMarketOpen = regularMarketOpen;
  }

  public YahooField getRegularMarketDayLow() {
    return regularMarketDayLow;
  }

  public void setRegularMarketDayLow(YahooField regularMarketDayLow) {
    this.regularMarketDayLow = regularMarketDayLow;
  }

  public YahooField getRegularMarketDayHigh() {
    return regularMarketDayHigh;
  }

  public void setRegularMarketDayHigh(YahooField regularMarketDayHigh) {
    this.regularMarketDayHigh = regularMarketDayHigh;
  }

  public YahooField getBid() {
    return bid;
  }

  public void setBid(YahooField bid) {
    this.bid = bid;
  }

  public YahooField getAsk() {
    return ask;
  }

  public void setAsk(YahooField ask) {
    this.ask = ask;
  }

  public YahooField getExpireDate() {
    return expireDate;
  }

  public void setExpireDate(YahooField expireDate) {
    this.expireDate = expireDate;
  }

  public YahooField getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(YahooField strikePrice) {
    this.strikePrice = strikePrice;
  }

  public YahooField getFiftyTwoWeekLow() {
    return fiftyTwoWeekLow;
  }

  public void setFiftyTwoWeekLow(YahooField fiftyTwoWeekLow) {
    this.fiftyTwoWeekLow = fiftyTwoWeekLow;
  }

  public YahooField getFiftyTwoWeekHigh() {
    return fiftyTwoWeekHigh;
  }

  public void setFiftyTwoWeekHigh(YahooField fiftyTwoWeekHigh) {
    this.fiftyTwoWeekHigh = fiftyTwoWeekHigh;
  }

  public YahooLongFormatField getOpenInterest() {
    return openInterest;
  }

  public void setOpenInterest(YahooLongFormatField openInterest) {
    this.openInterest = openInterest;
  }

  public YahooLongFormatField getVolume() {
    return volume;
  }

  public void setVolume(YahooLongFormatField volume) {
    this.volume = volume;
  }

  public YahooLongFormatField getRegularMarketVolume() {
    return regularMarketVolume;
  }

  public void setRegularMarketVolume(YahooLongFormatField regularMarketVolume) {
    this.regularMarketVolume = regularMarketVolume;
  }
}
