package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=balanceSheetHistory"
 * key to find in jackson: balanceSheetStatements
 * BalanceSheetStatement will have list of objects will be called balanceSheetStatements
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BalanceSheetStatement extends CompanyData implements Serializable {
  
  @JsonProperty("endDate")
  @EntityParameter(name = "End date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField endDate;

  @JsonProperty("cash")
  @EntityParameter(name = "Cash", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField cash;

  @JsonProperty("shortTermInvestments")
  @EntityParameter(name = "Short term investments", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField shortTermInvestments;

  @JsonProperty("netReceivables")
  @EntityParameter(name = "Net receivables", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField netReceivables;

  @JsonProperty("inventory")
  @EntityParameter(name = "Inventory", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField inventory;

  @JsonProperty("otherCurrentAssets")
  @EntityParameter(name = "Other current assets", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherCurrentAssets;

  @JsonProperty("totalCurrentAssets")
  @EntityParameter(name = "Total current assets", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalCurrentAssets;

  @JsonProperty("longTermInvestments")
  @EntityParameter(name = "Long term investments", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField longTermInvestments;

  @JsonProperty("propertyPlantEquipment")
  @EntityParameter(name = "Property plan equipment", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField propertyPlantEquipment;

  @JsonProperty("goodWill")
  @EntityParameter(name = "Good will", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField goodWill;

  @JsonProperty("intangibleAssets")
  @EntityParameter(name = "Intangible assets", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField intangibleAssets;

  @JsonProperty("otherAssets")
  @EntityParameter(name = "Other assets", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherAssets;

  @JsonProperty("totalAssets")
  @EntityParameter(name = "Total assets", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalAssets;

  @JsonProperty("accountsPayable")
  @EntityParameter(name = "Accounts payable", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField accountsPayable;

  @JsonProperty("shortLongTermDebt")
  @EntityParameter(name = "Short/Long term debt", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField shortLongTermDebt;

  @JsonProperty("otherCurrentLiab")
  @EntityParameter(name = "Other current liability", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherCurrentLiab;

  @JsonProperty("longTermDebt")
  @EntityParameter(name = "Long term debt", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField longTermDebt;

  @JsonProperty("otherLiab")
  @EntityParameter(name = "Other liabilities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherLiab;

  @JsonProperty("deferredLongTermLiab")
  @EntityParameter(name = "Deferred long term liability", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField deferredLongTermLiab;

  @JsonProperty("totalCurrentLiabilities")
  @EntityParameter(name = "Total current liabilities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalCurrentLiabilities;

  @JsonProperty("totalLiab")
  @EntityParameter(name = "Total liability", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalLiab;

  @JsonProperty("commonStock")
  @EntityParameter(name = "Common stock", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField commonStock;

  @JsonProperty("retainedEarnings")
  @EntityParameter(name = "Retained earnings", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField retainedEarnings;

  @JsonProperty("otherStockholderEquity")
  @EntityParameter(name = "Other stock holder equity", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherStockholderEquity;

  @JsonProperty("totalStockholderEquity")
  @EntityParameter(name = "Total stock holder equity", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalStockholderEquity;

  @JsonProperty("netTangibleAssets")
  @EntityParameter(name = "Net tangible assets", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField netTangibleAssets;

  public YahooField getEndDate() {
    return endDate;
  }

  public void setEndDate(YahooField endDate) {
    this.endDate = endDate;
  }

  public YahooLongFormatField getCash() {
    return cash;
  }

  public void setCash(YahooLongFormatField cash) {
    this.cash = cash;
  }

  public YahooLongFormatField getShortTermInvestments() {
    return shortTermInvestments;
  }

  public void setShortTermInvestments(YahooLongFormatField shortTermInvestments) {
    this.shortTermInvestments = shortTermInvestments;
  }

  public YahooLongFormatField getNetReceivables() {
    return netReceivables;
  }

  public void setNetReceivables(YahooLongFormatField netReceivables) {
    this.netReceivables = netReceivables;
  }

  public YahooLongFormatField getInventory() {
    return inventory;
  }

  public void setInventory(YahooLongFormatField inventory) {
    this.inventory = inventory;
  }

  public YahooLongFormatField getOtherCurrentAssets() {
    return otherCurrentAssets;
  }

  public void setOtherCurrentAssets(YahooLongFormatField otherCurrentAssets) {
    this.otherCurrentAssets = otherCurrentAssets;
  }

  public YahooLongFormatField getTotalCurrentAssets() {
    return totalCurrentAssets;
  }

  public void setTotalCurrentAssets(YahooLongFormatField totalCurrentAssets) {
    this.totalCurrentAssets = totalCurrentAssets;
  }

  public YahooLongFormatField getLongTermInvestments() {
    return longTermInvestments;
  }

  public void setLongTermInvestments(YahooLongFormatField longTermInvestments) {
    this.longTermInvestments = longTermInvestments;
  }

  public YahooLongFormatField getPropertyPlantEquipment() {
    return propertyPlantEquipment;
  }

  public void setPropertyPlantEquipment(YahooLongFormatField propertyPlantEquipment) {
    this.propertyPlantEquipment = propertyPlantEquipment;
  }

  public YahooLongFormatField getGoodWill() {
    return goodWill;
  }

  public void setGoodWill(YahooLongFormatField goodWill) {
    this.goodWill = goodWill;
  }

  public YahooLongFormatField getIntangibleAssets() {
    return intangibleAssets;
  }

  public void setIntangibleAssets(YahooLongFormatField intangibleAssets) {
    this.intangibleAssets = intangibleAssets;
  }

  public YahooLongFormatField getOtherAssets() {
    return otherAssets;
  }

  public void setOtherAssets(YahooLongFormatField otherAssets) {
    this.otherAssets = otherAssets;
  }

  public YahooLongFormatField getTotalAssets() {
    return totalAssets;
  }

  public void setTotalAssets(YahooLongFormatField totalAssets) {
    this.totalAssets = totalAssets;
  }

  public YahooLongFormatField getAccountsPayable() {
    return accountsPayable;
  }

  public void setAccountsPayable(YahooLongFormatField accountsPayable) {
    this.accountsPayable = accountsPayable;
  }

  public YahooLongFormatField getShortLongTermDebt() {
    return shortLongTermDebt;
  }

  public void setShortLongTermDebt(YahooLongFormatField shortLongTermDebt) {
    this.shortLongTermDebt = shortLongTermDebt;
  }

  public YahooLongFormatField getOtherCurrentLiab() {
    return otherCurrentLiab;
  }

  public void setOtherCurrentLiab(YahooLongFormatField otherCurrentLiab) {
    this.otherCurrentLiab = otherCurrentLiab;
  }

  public YahooLongFormatField getLongTermDebt() {
    return longTermDebt;
  }

  public void setLongTermDebt(YahooLongFormatField longTermDebt) {
    this.longTermDebt = longTermDebt;
  }

  public YahooLongFormatField getOtherLiab() {
    return otherLiab;
  }

  public void setOtherLiab(YahooLongFormatField otherLiab) {
    this.otherLiab = otherLiab;
  }

  public YahooLongFormatField getDeferredLongTermLiab() {
    return deferredLongTermLiab;
  }

  public void setDeferredLongTermLiab(YahooLongFormatField deferredLongTermLiab) {
    this.deferredLongTermLiab = deferredLongTermLiab;
  }

  public YahooLongFormatField getTotalCurrentLiabilities() {
    return totalCurrentLiabilities;
  }

  public void setTotalCurrentLiabilities(YahooLongFormatField totalCurrentLiabilities) {
    this.totalCurrentLiabilities = totalCurrentLiabilities;
  }

  public YahooLongFormatField getTotalLiab() {
    return totalLiab;
  }

  public void setTotalLiab(YahooLongFormatField totalLiab) {
    this.totalLiab = totalLiab;
  }

  public YahooLongFormatField getCommonStock() {
    return commonStock;
  }

  public void setCommonStock(YahooLongFormatField commonStock) {
    this.commonStock = commonStock;
  }

  public YahooLongFormatField getRetainedEarnings() {
    return retainedEarnings;
  }

  public void setRetainedEarnings(YahooLongFormatField retainedEarnings) {
    this.retainedEarnings = retainedEarnings;
  }

  public YahooLongFormatField getOtherStockholderEquity() {
    return otherStockholderEquity;
  }

  public void setOtherStockholderEquity(YahooLongFormatField otherStockholderEquity) {
    this.otherStockholderEquity = otherStockholderEquity;
  }

  public YahooLongFormatField getTotalStockholderEquity() {
    return totalStockholderEquity;
  }

  public void setTotalStockholderEquity(YahooLongFormatField totalStockholderEquity) {
    this.totalStockholderEquity = totalStockholderEquity;
  }

  public YahooLongFormatField getNetTangibleAssets() {
    return netTangibleAssets;
  }

  public void setNetTangibleAssets(YahooLongFormatField netTangibleAssets) {
    this.netTangibleAssets = netTangibleAssets;
  }
}
