package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=calendarEvents"
 * key to find in jackson: calendarEvents
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class CalendarEvents extends CompanyData implements Serializable {

  @JsonProperty("earnings")
  @EntityParameter(name = "Earnings", parameterType = ParameterType.INNER_CLASS, isMaster = true)
  private Earnings earnings;

  @JsonProperty("exDividendDate")
  @EntityParameter(name = "Ex dividend date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField exDividendDate;

  @JsonProperty("dividendDate")
  @EntityParameter(name = "Dividend date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField dividendDate;


  public YahooField getExDividendDate() {
    return exDividendDate;
  }

  public void setExDividendDate(YahooField exDividendDate) {
    this.exDividendDate = exDividendDate;
  }

  public YahooField getDividendDate() {
    return dividendDate;
  }

  public void setDividendDate(YahooField dividendDate) {
    this.dividendDate = dividendDate;
  }

  public Earnings getEarnings() {
    return earnings;
  }

  public void setEarnings(Earnings earnings) {
    this.earnings = earnings;
    if(this.earnings != null) {
      this.earnings.set();
    }
  }
}
