package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=calendarEvents"
 * key to find in jackson: calendarEvents
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class CalendarEvents extends CompanyData implements Serializable {

  @JsonProperty("earnings")
  @EntityParameter(name = "Earnings", parameterType = ParameterType.INNER_CLASS)
  private Earnings earnings;

  @JsonProperty("exDividendDate")
  @EntityParameter(name = "Ex dividend date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField exDividendDate;

  @JsonProperty("dividendDate")
  @EntityParameter(name = "Dividend date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField dividendDate;

  public ArrayList<YahooField> getEarningsDate() {
    return this.earnings.getEarningsDate();
  }

  public void setEarningsDate(ArrayList<YahooField> earningsDate) {
    this.earnings.setEarningsDate(earningsDate);
  }

  public YahooField getEarningsAverage() {
    return this.earnings.getEarningsAverage();
  }

  public void setEarningsAverage(YahooField earningsAverage) {
    this.earnings.setEarningsAverage(earningsAverage);
  }

  public YahooField getEarningsLow() {
    return this.earnings.getEarningsLow();
  }

  public void setEarningsLow(YahooField earningsLow) {
    this.earnings.setEarningsLow(earningsLow);
  }

  public YahooField getEarningsHigh() {
    return this.earnings.getEarningsHigh();
  }

  public void setEarningsHigh(YahooField earningsHigh) {
    this.earnings.setEarningsHigh(earningsHigh);
  }

  public YahooLongFormatField getRevenueAverage() {
    return this.earnings.getRevenueAverage();
  }

  public void setRevenueAverage(YahooLongFormatField revenueAverage) {
    this.earnings.setRevenueAverage(revenueAverage);
  }

  public YahooLongFormatField getRevenueLow() {
    return this.earnings.getRevenueLow();
  }

  public YahooLongFormatField getRevenueHigh() {
    return this.earnings.getRevenueHigh();
  }

  public void setRevenueLow(YahooLongFormatField revenueLow) {
    this.earnings.setRevenueLow(revenueLow);
  }

  public YahooField getExDividendDate() {
    return exDividendDate;
  }

  public void setExDividendDate(YahooField exDividendDate) {
    this.exDividendDate = exDividendDate;
  }

  public YahooField getDividendDate() {
    return dividendDate;
  }

  public void setDividendDate(YahooField dividendDate) {
    this.dividendDate = dividendDate;
  }

  public Earnings getEarnings() {
    return earnings;
  }

  public void setEarnings(Earnings earnings) {
    this.earnings = earnings;
  }
}
