package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=cashflowStatementHistory"
 * key to find in jackson: cashflowStatements
 * CashFlowStatement will have list of objects will be called CashFlowStatements
 *
 * @author Yago Rodríguez
 */

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class CashFlowStatement extends CompanyData implements Serializable {

  @JsonProperty("endDate")
  @EntityParameter(name = "End date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField endDate;
  
  @JsonProperty("netIncome")  
  @EntityParameter(name = "Net income", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField netIncome;
  
  @JsonProperty("depreciation")
  @EntityParameter(name = "Depreciation", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField depreciation;
  
  @JsonProperty("changeToNetincome")
  @EntityParameter(name = "Change to net income", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField changeToNetincome;
  
  @JsonProperty("changeToAccountReceivables")
  @EntityParameter(name = "Change to Account Receivables", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField changeToAccountReceivables;
  
  @JsonProperty("changeToLiabilities")
  @EntityParameter(name = "Change to liabilities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField changeToLiabilities;
  
  @JsonProperty("changeToInventory")
  @EntityParameter(name = "Change to inventory", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField changeToInventory;
  
  @JsonProperty("changeToOperatingActivities")
  @EntityParameter(name = "Change to operating activities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField changeToOperatingActivities;
  
  @JsonProperty("totalCashFromOperatingActivities")
  @EntityParameter(name = "Total cash from operating activities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalCashFromOperatingActivities;
  
  @JsonProperty("capitalExpenditures")
  @EntityParameter(name = "Capital Expenditures", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField capitalExpenditures;
  
  @JsonProperty("investments")
  @EntityParameter(name = "Investments", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField investments;
  
  @JsonProperty("otherCashflowsFromInvestingActivities")
  @EntityParameter(name = "Other cashflows from investing", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherCashflowsFromInvestingActivities;

  @JsonProperty("totalCashflowsFromInvestingActivities")
  @EntityParameter(name = "Total cashflow from investing activities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalCashflowsFromInvestingActivities;

  @JsonProperty("dividendsPaid")
  @EntityParameter(name = "Dividends paid", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField dividendsPaid;

  @JsonProperty("salePurchaseOfStock")
  @EntityParameter(name = "Sale purchase of stock", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField salePurchaseOfStock;

  @JsonProperty("netBorrowings")
  @EntityParameter(name = "Net borrowings", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField netBorrowings;

  @JsonProperty("otherCashflowsFromFinancingActivities")
  @EntityParameter(name = "Other cashflows from financing activities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField otherCashflowsFromFinancingActivities;

  @JsonProperty("totalCashFromFinancingActivities")
  @EntityParameter(name = "Total cash from financing activities", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalCashFromFinancingActivities;

  @JsonProperty("changeInCash")
  @EntityParameter(name = "Change In cash", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField changeInCash;

  public YahooField getEndDate() {
    return endDate;
  }

  public void setEndDate(YahooField endDate) {
    this.endDate = endDate;
  }

  public YahooLongFormatField getNetIncome() {
    return netIncome;
  }

  public void setNetIncome(YahooLongFormatField netIncome) {
    this.netIncome = netIncome;
  }

  public YahooLongFormatField getDepreciation() {
    return depreciation;
  }

  public void setDepreciation(YahooLongFormatField depreciation) {
    this.depreciation = depreciation;
  }

  public YahooLongFormatField getChangeToNetincome() {
    return changeToNetincome;
  }

  public void setChangeToNetincome(YahooLongFormatField changeToNetincome) {
    this.changeToNetincome = changeToNetincome;
  }

  public YahooLongFormatField getChangeToAccountReceivables() {
    return changeToAccountReceivables;
  }

  public void setChangeToAccountReceivables(YahooLongFormatField changeToAccountReceivables) {
    this.changeToAccountReceivables = changeToAccountReceivables;
  }

  public YahooLongFormatField getChangeToLiabilities() {
    return changeToLiabilities;
  }

  public void setChangeToLiabilities(YahooLongFormatField changeToLiabilities) {
    this.changeToLiabilities = changeToLiabilities;
  }

  public YahooLongFormatField getChangeToInventory() {
    return changeToInventory;
  }

  public void setChangeToInventory(YahooLongFormatField changeToInventory) {
    this.changeToInventory = changeToInventory;
  }

  public YahooLongFormatField getChangeToOperatingActivities() {
    return changeToOperatingActivities;
  }

  public void setChangeToOperatingActivities(YahooLongFormatField changeToOperatingActivities) {
    this.changeToOperatingActivities = changeToOperatingActivities;
  }

  public YahooLongFormatField getTotalCashFromOperatingActivities() {
    return totalCashFromOperatingActivities;
  }

  public void setTotalCashFromOperatingActivities(YahooLongFormatField totalCashFromOperatingActivities) {
    this.totalCashFromOperatingActivities = totalCashFromOperatingActivities;
  }

  public YahooLongFormatField getCapitalExpenditures() {
    return capitalExpenditures;
  }

  public void setCapitalExpenditures(YahooLongFormatField capitalExpenditures) {
    this.capitalExpenditures = capitalExpenditures;
  }

  public YahooLongFormatField getInvestments() {
    return investments;
  }

  public void setInvestments(YahooLongFormatField investments) {
    this.investments = investments;
  }

  public YahooLongFormatField getOtherCashflowsFromInvestingActivities() {
    return otherCashflowsFromInvestingActivities;
  }

  public void setOtherCashflowsFromInvestingActivities(YahooLongFormatField otherCashflowsFromInvestingActivities) {
    this.otherCashflowsFromInvestingActivities = otherCashflowsFromInvestingActivities;
  }

  public YahooLongFormatField getTotalCashflowsFromInvestingActivities() {
    return totalCashflowsFromInvestingActivities;
  }

  public void setTotalCashflowsFromInvestingActivities(YahooLongFormatField totalCashflowsFromInvestingActivities) {
    this.totalCashflowsFromInvestingActivities = totalCashflowsFromInvestingActivities;
  }

  public YahooLongFormatField getDividendsPaid() {
    return dividendsPaid;
  }

  public void setDividendsPaid(YahooLongFormatField dividendsPaid) {
    this.dividendsPaid = dividendsPaid;
  }

  public YahooLongFormatField getSalePurchaseOfStock() {
    return salePurchaseOfStock;
  }

  public void setSalePurchaseOfStock(YahooLongFormatField salePurchaseOfStock) {
    this.salePurchaseOfStock = salePurchaseOfStock;
  }

  public YahooLongFormatField getNetBorrowings() {
    return netBorrowings;
  }

  public void setNetBorrowings(YahooLongFormatField netBorrowings) {
    this.netBorrowings = netBorrowings;
  }

  public YahooLongFormatField getOtherCashflowsFromFinancingActivities() {
    return otherCashflowsFromFinancingActivities;
  }

  public void setOtherCashflowsFromFinancingActivities(YahooLongFormatField otherCashflowsFromFinancingActivities) {
    this.otherCashflowsFromFinancingActivities = otherCashflowsFromFinancingActivities;
  }

  public YahooLongFormatField getTotalCashFromFinancingActivities() {
    return totalCashFromFinancingActivities;
  }

  public void setTotalCashFromFinancingActivities(YahooLongFormatField totalCashFromFinancingActivities) {
    this.totalCashFromFinancingActivities = totalCashFromFinancingActivities;
  }

  public YahooLongFormatField getChangeInCash() {
    return changeInCash;
  }

  public void setChangeInCash(YahooLongFormatField changeInCash) {
    this.changeInCash = changeInCash;
  }
}
