package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=defaultKeyStatistics"
 * key to find in jackson: defaultKeyStatistics
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class DefaultKeyStatistics extends CompanyData implements Serializable {

  @JsonProperty("lastSplitFactor")
  @EntityParameter(name = "Last split factor", parameterType = ParameterType.RAW_STRING, allowedValues = LastSplitFactorAllowedValues.class)
  private String lastSplitFactor;

  @JsonProperty("forwardPE")
  @EntityParameter(name = "Forward price to earnings", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField forwardPE;

  @JsonProperty("profitMargins")
  @EntityParameter(name = "Profit margins", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField profitMargins;

  @JsonProperty("heldPercentInsiders")
  @EntityParameter(name = "Held percent insiders", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField heldPercentInsiders;

  @JsonProperty("heldPercentInstitutions")
  @EntityParameter(name = "Held percent institutions", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField heldPercentInstitutions;

  @JsonProperty("shortRatio")
  @EntityParameter(name = "Short ratio", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField shortRatio;

  @JsonProperty("shortPercentOfFloat")
  @EntityParameter(name = "Short percent of float", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField shortPercentOfFloat;

  @JsonProperty("beta")
  @EntityParameter(name = "Beta", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField beta;

  @JsonProperty("bookValue")
  @EntityParameter(name = "Book name", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField bookValue;

  @JsonProperty("priceToBook")
  @EntityParameter(name = "Price to book", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField priceToBook;

  @JsonProperty("lastFiscalYearEnd")
  @EntityParameter(name = "Last fiscal Year End", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField lastFiscalYearEnd;

  @JsonProperty("nextFiscalYearEnd")
  @EntityParameter(name = "Next fiscal year End", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField nextFiscalYearEnd;

  @JsonProperty("mostRecentQuarter")
  @EntityParameter(name = "Most recent quarter", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField mostRecentQuarter;

  @JsonProperty("earningsQuarterlyGrowth")
  @EntityParameter(name = "Earnings quarterly growth", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField earningsQuarterlyGrowth;

  @JsonProperty("trailingEps")
  @EntityParameter(name = "Trailing EPS", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField trailingEps;

  @JsonProperty("forwardEps")
  @EntityParameter(name = "Forward EPS", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField forwardEps;

  @JsonProperty("pegRatio")
  @EntityParameter(name = "PEG ratio", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField pegRatio;

  @JsonProperty("lastSplitDate")
  @EntityParameter(name = "Last split date", parameterType = ParameterType.YAHOO_FIELD_DATE)
  private YahooField lastSplitDate;

  @JsonProperty("enterpriseToRevenue")
  @EntityParameter(name = "Enterprise to revenue", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField enterpriseToRevenue;

  @JsonProperty("enterpriseToEbitda")
  @EntityParameter(name = "Entrprise EBITDA", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField enterpriseToEbitda;

  @JsonProperty("SandP52WeekChange")
  @EntityParameter(name = "Sand 52 week change", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField sandP52WeekChange;

  @JsonProperty("floatShares")
  @EntityParameter(name = "Float shares", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField floatShares;

  @JsonProperty("sharesOutstanding")
  @EntityParameter(name = "Shares outstanding", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField sharesOutstanding;

  @JsonProperty("sharesShort")
  @EntityParameter(name = "Shares short", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField sharesShort;

  @JsonProperty("sharesShortPriorMonth")
  @EntityParameter(name = "Shares short prior month", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField sharesShortPriorMonth;

  @JsonProperty("netIncomeToCommon")
  @EntityParameter(name = "ROE", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField netIncomeToCommon;

  @JsonProperty("enterpriseValue")
  @EntityParameter(name = "Enterprise value", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD, isMaster = true)
  private YahooLongFormatField enterpriseValue;

  public String getLastSplitFactor() {
    return lastSplitFactor;
  }

  public void setLastSplitFactor(String lastSplitFactor) {
    this.lastSplitFactor = lastSplitFactor;
  }

  public YahooField getForwardPE() {
    return forwardPE;
  }

  public void setForwardPE(YahooField forwardPE) {
    this.forwardPE = forwardPE;
  }

  public YahooField getProfitMargins() {
    return profitMargins;
  }

  public void setProfitMargins(YahooField profitMargins) {
    this.profitMargins = profitMargins;
  }

  public YahooField getHeldPercentInsiders() {
    return heldPercentInsiders;
  }

  public void setHeldPercentInsiders(YahooField heldPercentInsiders) {
    this.heldPercentInsiders = heldPercentInsiders;
  }

  public YahooField getHeldPercentInstitutions() {
    return heldPercentInstitutions;
  }

  public void setHeldPercentInstitutions(YahooField heldPercentInstitutions) {
    this.heldPercentInstitutions = heldPercentInstitutions;
  }

  public YahooField getShortRatio() {
    return shortRatio;
  }

  public void setShortRatio(YahooField shortRatio) {
    this.shortRatio = shortRatio;
  }

  public YahooField getShortPercentOfFloat() {
    return shortPercentOfFloat;
  }

  public void setShortPercentOfFloat(YahooField shortPercentOfFloat) {
    this.shortPercentOfFloat = shortPercentOfFloat;
  }

  public YahooField getBeta() {
    return beta;
  }

  public void setBeta(YahooField beta) {
    this.beta = beta;
  }

  public YahooField getBookValue() {
    return bookValue;
  }

  public void setBookValue(YahooField bookValue) {
    this.bookValue = bookValue;
  }

  public YahooField getPriceToBook() {
    return priceToBook;
  }

  public void setPriceToBook(YahooField priceToBook) {
    this.priceToBook = priceToBook;
  }

  public YahooField getLastFiscalYearEnd() {
    return lastFiscalYearEnd;
  }

  public void setLastFiscalYearEnd(YahooField lastFiscalYearEnd) {
    this.lastFiscalYearEnd = lastFiscalYearEnd;
  }

  public YahooField getNextFiscalYearEnd() {
    return nextFiscalYearEnd;
  }

  public void setNextFiscalYearEnd(YahooField nextFiscalYearEnd) {
    this.nextFiscalYearEnd = nextFiscalYearEnd;
  }

  public YahooField getMostRecentQuarter() {
    return mostRecentQuarter;
  }

  public void setMostRecentQuarter(YahooField mostRecentQuarter) {
    this.mostRecentQuarter = mostRecentQuarter;
  }

  public YahooField getEarningsQuarterlyGrowth() {
    return earningsQuarterlyGrowth;
  }

  public void setEarningsQuarterlyGrowth(YahooField earningsQuarterlyGrowth) {
    this.earningsQuarterlyGrowth = earningsQuarterlyGrowth;
  }

  public YahooField getTrailingEps() {
    return trailingEps;
  }

  public void setTrailingEps(YahooField trailingEps) {
    this.trailingEps = trailingEps;
  }

  public YahooField getForwardEps() {
    return forwardEps;
  }

  public void setForwardEps(YahooField forwardEps) {
    this.forwardEps = forwardEps;
  }

  public YahooField getPegRatio() {
    return pegRatio;
  }

  public void setPegRatio(YahooField pegRatio) {
    this.pegRatio = pegRatio;
  }

  public YahooField getLastSplitDate() {
    return lastSplitDate;
  }

  public void setLastSplitDate(YahooField lastSplitDate) {
    this.lastSplitDate = lastSplitDate;
  }

  public YahooField getEnterpriseToRevenue() {
    return enterpriseToRevenue;
  }

  public void setEnterpriseToRevenue(YahooField enterpriseToRevenue) {
    this.enterpriseToRevenue = enterpriseToRevenue;
  }

  public YahooField getEnterpriseToEbitda() {
    return enterpriseToEbitda;
  }

  public void setEnterpriseToEbitda(YahooField enterpriseToEbitda) {
    this.enterpriseToEbitda = enterpriseToEbitda;
  }

  public YahooField getSandP52WeekChange() {
    return sandP52WeekChange;
  }

  public void setSandP52WeekChange(YahooField sandP52WeekChange) {
    this.sandP52WeekChange = sandP52WeekChange;
  }

  public YahooLongFormatField getFloatShares() {
    return floatShares;
  }

  public void setFloatShares(YahooLongFormatField floatShares) {
    this.floatShares = floatShares;
  }

  public YahooLongFormatField getSharesOutstanding() {
    return sharesOutstanding;
  }

  public void setSharesOutstanding(YahooLongFormatField sharesOutstanding) {
    this.sharesOutstanding = sharesOutstanding;
  }

  public YahooLongFormatField getSharesShort() {
    return sharesShort;
  }

  public void setSharesShort(YahooLongFormatField sharesShort) {
    this.sharesShort = sharesShort;
  }

  public YahooLongFormatField getSharesShortPriorMonth() {
    return sharesShortPriorMonth;
  }

  public void setSharesShortPriorMonth(YahooLongFormatField sharesShortPriorMonth) {
    this.sharesShortPriorMonth = sharesShortPriorMonth;
  }

  public YahooLongFormatField getNetIncomeToCommon() {
    return netIncomeToCommon;
  }

  public void setNetIncomeToCommon(YahooLongFormatField netIncomeToCommon) {
    this.netIncomeToCommon = netIncomeToCommon;
  }

  public YahooLongFormatField getEnterpriseValue() {
    return enterpriseValue;
  }

  public void setEnterpriseValue(YahooLongFormatField enterpriseValue) {
    this.enterpriseValue = enterpriseValue;
  }



  /*
  * *** NULL DATA ***
  @JsonProperty("revenueQuarterlyGrowth")
  private EntityParameter revenueQuarterlyGrowth;
  @JsonProperty("morningStarOverallRating")
  private EntityParameter morningStarOverallRating;
  @JsonProperty("morningStarRiskRating")
  private EntityParameter morningStarRiskRating;
  @JsonProperty("category")
  private EntityParameter category; // null,
  @JsonProperty("annualReportExpenseRatio")
  private EntityParameter annualReportExpenseRatio;
  @JsonProperty("ytdReturn")
  private EntityParameter ytdReturn;
  @JsonProperty("beta3Year")
  private EntityParameter beta3Year;
  @JsonProperty("totalAssets")
  private EntityParameter totalAssets;
  @JsonProperty("yield")
  private EntityParameter yield;
  @JsonProperty("fundFamily")
  private EntityParameter fundFamily; // null,
  @JsonProperty("fundInceptionDate")
  private EntityParameter fundInceptionDate;
  @JsonProperty("legalType")
  private EntityParameter legalType; // null,
  @JsonProperty("threeYearAverageReturn")
  private EntityParameter threeYearAverageReturn;
  @JsonProperty("fiveYearAverageReturn")
  private EntityParameter fiveYearAverageReturn;
  @JsonProperty("priceToSalesTrailing12Months")
  private EntityParameter priceToSalesTrailing12Months;
  @JsonProperty("lastDividendValue")
  private EntityParameter lastDividendValue;
  @JsonProperty("lastCapGain")
  private EntityParameter lastCapGain;
  @JsonProperty("annualHoldingsTurnover")
  private EntityParameter annualHoldingsTurnover;
   */

}
