package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.FieldType;
import es.usefulearnings.annotation.ObservableField;
import es.usefulearnings.entities.Field;
import es.usefulearnings.entities.LongFormatField;
/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=financialData"
 * key to find in jackson: financialData
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class FinancialData extends CompanyData {

  @JsonProperty("currentPrice")
  @ObservableField(name = "Current price", fieldType = FieldType.NUMERIC)
  private Field currentPrice;

  @JsonProperty("targetHighPrice")
  @ObservableField(name = "Target high price", fieldType = FieldType.NUMERIC)
  private Field targetHighPrice;

  @JsonProperty("targetLowPrice")
  @ObservableField(name = "Target low price", fieldType = FieldType.NUMERIC)
  private Field targetLowPrice;

  @JsonProperty("targetMeanPrice")
  @ObservableField(name = "Target mean price", fieldType = FieldType.NUMERIC)
  private Field targetMeanPrice;

  @JsonProperty("targetMedianPrice")
  @ObservableField(name = "Target median price", fieldType = FieldType.NUMERIC)
  private Field targetMedianPrice;

  @JsonProperty("recommendationMean")
  @ObservableField(name = "Recommendation mean", fieldType = FieldType.NUMERIC)
  private Field recommendationMean;

  @JsonProperty("recommendationKey")
  @ObservableField(name = "Recommendation key", fieldType = FieldType.STRING)
  private String recommendationKey;

  @JsonProperty("totalCashPerShare")
  @ObservableField(name = "Total cash per share", fieldType = FieldType.NUMERIC)
  private Field totalCashPerShare;

  @JsonProperty("quickRatio")
  @ObservableField(name = "Quick ratio", fieldType = FieldType.NUMERIC)
  private Field quickRatio;

  @JsonProperty("currentRatio")
  @ObservableField(name = "Current ratio", fieldType = FieldType.NUMERIC)
  private Field currentRatio;

  @JsonProperty("returnOnAssets")
  @ObservableField(name = "Return on assets", fieldType = FieldType.NUMERIC)
  private Field returnOnAssets;

  @JsonProperty("returnOnEquity")
  @ObservableField(name = "Return on Equity", fieldType = FieldType.NUMERIC)
  private Field returnOnEquity;

  @JsonProperty("earningsGrowth")
  @ObservableField(name = "Earnings growth", fieldType = FieldType.NUMERIC)
  private Field earningsGrowth;

  @JsonProperty("revenueGrowth")
  @ObservableField(name = "Revenue growth", fieldType = FieldType.NUMERIC)
  private Field revenueGrowth;

  @JsonProperty("grossMargins")
  @ObservableField(name = "Gross margins", fieldType = FieldType.NUMERIC)
  private Field grossMargins;

  @JsonProperty("ebitdaMargins")
  @ObservableField(name = "EBITDA margins", fieldType = FieldType.NUMERIC)
  private Field ebitdaMargins;

  @JsonProperty("operatingMargins")
  @ObservableField(name = "Operating margins", fieldType = FieldType.NUMERIC)
  private Field operatingMargins;

  @JsonProperty("profitMargins")
  @ObservableField(name = "Profit margins", fieldType = FieldType.NUMERIC)
  private Field profitMargins;

  @JsonProperty("numberOfAnalystOpinions")
  @ObservableField(name = "Number of analyst opinions", fieldType = FieldType.NUMERIC)
  private LongFormatField numberOfAnalystOpinions;

  @JsonProperty("totalCash")
  @ObservableField(name = "", fieldType = FieldType.NUMERIC)
  private LongFormatField totalCash;

  @JsonProperty("ebitda")
  @ObservableField(name = "EBITDA", fieldType = FieldType.NUMERIC)
  private LongFormatField ebitda;

 @JsonProperty("totalDebt")
 @ObservableField(name = "Total debt", fieldType = FieldType.NUMERIC)
  private LongFormatField totalDebt;

  @JsonProperty("totalRevenue")
  @ObservableField(name = "Total revenue", fieldType = FieldType.NUMERIC)
  private LongFormatField totalRevenue;

  @JsonProperty("debtToEquity")
  @ObservableField(name = "Debt to equity", fieldType = FieldType.NUMERIC)
  private LongFormatField debtToEquity;

  @JsonProperty("grossProfits")
  @ObservableField(name = "Gross profits", fieldType = FieldType.NUMERIC)
  private LongFormatField grossProfits;

  @JsonProperty("freeCashflow")
  @ObservableField(name = "Free cashflow", fieldType = FieldType.NUMERIC)
  private LongFormatField freeCashflow;

  @JsonProperty("operatingCashflow")
  @ObservableField(name = "Operating cashflow", fieldType = FieldType.NUMERIC)
  private LongFormatField operatingCashflow;


  public Field getCurrentPrice() {
    return currentPrice;
  }

  public void setCurrentPrice(Field currentPrice) {
    this.currentPrice = currentPrice;
  }

  public Field getTargetHighPrice() {
    return targetHighPrice;
  }

  public void setTargetHighPrice(Field targetHighPrice) {
    this.targetHighPrice = targetHighPrice;
  }

  public Field getTargetLowPrice() {
    return targetLowPrice;
  }

  public void setTargetLowPrice(Field targetLowPrice) {
    this.targetLowPrice = targetLowPrice;
  }

  public Field getTargetMeanPrice() {
    return targetMeanPrice;
  }

  public void setTargetMeanPrice(Field targetMeanPrice) {
    this.targetMeanPrice = targetMeanPrice;
  }

  public Field getTargetMedianPrice() {
    return targetMedianPrice;
  }

  public void setTargetMedianPrice(Field targetMedianPrice) {
    this.targetMedianPrice = targetMedianPrice;
  }

  public Field getRecommendationMean() {
    return recommendationMean;
  }

  public void setRecommendationMean(Field recommendationMean) {
    this.recommendationMean = recommendationMean;
  }

  public String getRecommendationKey() {
    return recommendationKey;
  }

  public void setRecommendationKey(String recommendationKey) {
    this.recommendationKey = recommendationKey;
  }

  public Field getTotalCashPerShare() {
    return totalCashPerShare;
  }

  public void setTotalCashPerShare(Field totalCashPerShare) {
    this.totalCashPerShare = totalCashPerShare;
  }

  public Field getQuickRatio() {
    return quickRatio;
  }

  public void setQuickRatio(Field quickRatio) {
    this.quickRatio = quickRatio;
  }

  public Field getCurrentRatio() {
    return currentRatio;
  }

  public void setCurrentRatio(Field currentRatio) {
    this.currentRatio = currentRatio;
  }

  public Field getReturnOnAssets() {
    return returnOnAssets;
  }

  public void setReturnOnAssets(Field returnOnAssets) {
    this.returnOnAssets = returnOnAssets;
  }

  public Field getReturnOnEquity() {
    return returnOnEquity;
  }

  public void setReturnOnEquity(Field returnOnEquity) {
    this.returnOnEquity = returnOnEquity;
  }

  public Field getEarningsGrowth() {
    return earningsGrowth;
  }

  public void setEarningsGrowth(Field earningsGrowth) {
    this.earningsGrowth = earningsGrowth;
  }

  public Field getRevenueGrowth() {
    return revenueGrowth;
  }

  public void setRevenueGrowth(Field revenueGrowth) {
    this.revenueGrowth = revenueGrowth;
  }

  public Field getGrossMargins() {
    return grossMargins;
  }

  public void setGrossMargins(Field grossMargins) {
    this.grossMargins = grossMargins;
  }

  public Field getEbitdaMargins() {
    return ebitdaMargins;
  }

  public void setEbitdaMargins(Field ebitdaMargins) {
    this.ebitdaMargins = ebitdaMargins;
  }

  public Field getOperatingMargins() {
    return operatingMargins;
  }

  public void setOperatingMargins(Field operatingMargins) {
    this.operatingMargins = operatingMargins;
  }

  public Field getProfitMargins() {
    return profitMargins;
  }

  public void setProfitMargins(Field profitMargins) {
    this.profitMargins = profitMargins;
  }

  public LongFormatField getNumberOfAnalystOpinions() {
    return numberOfAnalystOpinions;
  }

  public void setNumberOfAnalystOpinions(LongFormatField numberOfAnalystOpinions) {
    this.numberOfAnalystOpinions = numberOfAnalystOpinions;
  }

  public LongFormatField getTotalCash() {
    return totalCash;
  }

  public void setTotalCash(LongFormatField totalCash) {
    this.totalCash = totalCash;
  }

  public LongFormatField getEbitda() {
    return ebitda;
  }

  public void setEbitda(LongFormatField ebitda) {
    this.ebitda = ebitda;
  }

  public LongFormatField getTotalDebt() {
    return totalDebt;
  }

  public void setTotalDebt(LongFormatField totalDebt) {
    this.totalDebt = totalDebt;
  }

  public LongFormatField getTotalRevenue() {
    return totalRevenue;
  }

  public void setTotalRevenue(LongFormatField totalRevenue) {
    this.totalRevenue = totalRevenue;
  }

  public LongFormatField getDebtToEquity() {
    return debtToEquity;
  }

  public void setDebtToEquity(LongFormatField debtToEquity) {
    this.debtToEquity = debtToEquity;
  }

  public LongFormatField getGrossProfits() {
    return grossProfits;
  }

  public void setGrossProfits(LongFormatField grossProfits) {
    this.grossProfits = grossProfits;
  }

  public LongFormatField getFreeCashflow() {
    return freeCashflow;
  }

  public void setFreeCashflow(LongFormatField freeCashflow) {
    this.freeCashflow = freeCashflow;
  }

  public LongFormatField getOperatingCashflow() {
    return operatingCashflow;
  }

  public void setOperatingCashflow(LongFormatField operatingCashflow) {
    this.operatingCashflow = operatingCashflow;
  }
}