package es.usefulearnings.entities.company;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.usefulearnings.annotation.EntityParameter;
import es.usefulearnings.annotation.ParameterType;
import es.usefulearnings.entities.YahooLongFormatField;
import es.usefulearnings.entities.YahooField;

import java.io.Serializable;

/**
 * Generated by: "https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?formatted=true&modules=financialData"
 * key to find in jackson: financialData
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class FinancialData extends CompanyData implements Serializable {

  @JsonProperty("currentPrice")
  @EntityParameter(name = "Current price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC, isMaster = true)
  private YahooField currentPrice;

  @JsonProperty("targetHighPrice")
  @EntityParameter(name = "Target high price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField targetHighPrice;

  @JsonProperty("targetLowPrice")
  @EntityParameter(name = "Target low price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField targetLowPrice;

  @JsonProperty("targetMeanPrice")
  @EntityParameter(name = "Target mean price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField targetMeanPrice;

  @JsonProperty("targetMedianPrice")
  @EntityParameter(name = "Target median price", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField targetMedianPrice;

  @JsonProperty("recommendationMean")
  @EntityParameter(name = "Recommendation mean", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField recommendationMean;

  @JsonProperty("recommendationKey")
  @EntityParameter(name = "Recommendation key", parameterType = ParameterType.RAW_STRING, allowedValues = RecommendationKeyAllowedValues.class)
  private String recommendationKey;

  @JsonProperty("totalCashPerShare")
  @EntityParameter(name = "Total cash per share", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField totalCashPerShare;

  @JsonProperty("quickRatio")
  @EntityParameter(name = "Quick ratio", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField quickRatio;

  @JsonProperty("currentRatio")
  @EntityParameter(name = "Current ratio", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField currentRatio;

  @JsonProperty("returnOnAssets")
  @EntityParameter(name = "Return on assets", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField returnOnAssets;

  @JsonProperty("returnOnEquity")
  @EntityParameter(name = "Return on Equity", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField returnOnEquity;

  @JsonProperty("earningsGrowth")
  @EntityParameter(name = "Earnings growth", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField earningsGrowth;

  @JsonProperty("revenueGrowth")
  @EntityParameter(name = "Revenue growth", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField revenueGrowth;

  @JsonProperty("grossMargins")
  @EntityParameter(name = "Gross margins", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField grossMargins;

  @JsonProperty("ebitdaMargins")
  @EntityParameter(name = "EBITDA margins", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField ebitdaMargins;

  @JsonProperty("operatingMargins")
  @EntityParameter(name = "Operating margins", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField operatingMargins;

  @JsonProperty("profitMargins")
  @EntityParameter(name = "Profit margins", parameterType = ParameterType.YAHOO_FIELD_NUMERIC)
  private YahooField profitMargins;

  @JsonProperty("numberOfAnalystOpinions")
  @EntityParameter(name = "Number of analyst opinions", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField numberOfAnalystOpinions;

  @JsonProperty("totalCash")
  @EntityParameter(name = "Total cash", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalCash;

  @JsonProperty("ebitda")
  @EntityParameter(name = "EBITDA", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField ebitda;

 @JsonProperty("totalDebt")
 @EntityParameter(name = "Total debt", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalDebt;

  @JsonProperty("totalRevenue")
  @EntityParameter(name = "Total revenue", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField totalRevenue;

  @JsonProperty("debtToEquity")
  @EntityParameter(name = "Debt to equity", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField debtToEquity;

  @JsonProperty("grossProfits")
  @EntityParameter(name = "Gross profits", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField grossProfits;

  @JsonProperty("freeCashflow")
  @EntityParameter(name = "Free cashflow", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField freeCashflow;

  @JsonProperty("operatingCashflow")
  @EntityParameter(name = "Operating cashflow", parameterType = ParameterType.YAHOO_LONG_FORMAT_FIELD)
  private YahooLongFormatField operatingCashflow;


  public YahooField getCurrentPrice() {
    return currentPrice;
  }

  public void setCurrentPrice(YahooField currentPrice) {
    this.currentPrice = currentPrice;
  }

  public YahooField getTargetHighPrice() {
    return targetHighPrice;
  }

  public void setTargetHighPrice(YahooField targetHighPrice) {
    this.targetHighPrice = targetHighPrice;
  }

  public YahooField getTargetLowPrice() {
    return targetLowPrice;
  }

  public void setTargetLowPrice(YahooField targetLowPrice) {
    this.targetLowPrice = targetLowPrice;
  }

  public YahooField getTargetMeanPrice() {
    return targetMeanPrice;
  }

  public void setTargetMeanPrice(YahooField targetMeanPrice) {
    this.targetMeanPrice = targetMeanPrice;
  }

  public YahooField getTargetMedianPrice() {
    return targetMedianPrice;
  }

  public void setTargetMedianPrice(YahooField targetMedianPrice) {
    this.targetMedianPrice = targetMedianPrice;
  }

  public YahooField getRecommendationMean() {
    return recommendationMean;
  }

  public void setRecommendationMean(YahooField recommendationMean) {
    this.recommendationMean = recommendationMean;
  }

  public String getRecommendationKey() {
    return recommendationKey;
  }

  public void setRecommendationKey(String recommendationKey) {
    this.recommendationKey = recommendationKey;
  }

  public YahooField getTotalCashPerShare() {
    return totalCashPerShare;
  }

  public void setTotalCashPerShare(YahooField totalCashPerShare) {
    this.totalCashPerShare = totalCashPerShare;
  }

  public YahooField getQuickRatio() {
    return quickRatio;
  }

  public void setQuickRatio(YahooField quickRatio) {
    this.quickRatio = quickRatio;
  }

  public YahooField getCurrentRatio() {
    return currentRatio;
  }

  public void setCurrentRatio(YahooField currentRatio) {
    this.currentRatio = currentRatio;
  }

  public YahooField getReturnOnAssets() {
    return returnOnAssets;
  }

  public void setReturnOnAssets(YahooField returnOnAssets) {
    this.returnOnAssets = returnOnAssets;
  }

  public YahooField getReturnOnEquity() {
    return returnOnEquity;
  }

  public void setReturnOnEquity(YahooField returnOnEquity) {
    this.returnOnEquity = returnOnEquity;
  }

  public YahooField getEarningsGrowth() {
    return earningsGrowth;
  }

  public void setEarningsGrowth(YahooField earningsGrowth) {
    this.earningsGrowth = earningsGrowth;
  }

  public YahooField getRevenueGrowth() {
    return revenueGrowth;
  }

  public void setRevenueGrowth(YahooField revenueGrowth) {
    this.revenueGrowth = revenueGrowth;
  }

  public YahooField getGrossMargins() {
    return grossMargins;
  }

  public void setGrossMargins(YahooField grossMargins) {
    this.grossMargins = grossMargins;
  }

  public YahooField getEbitdaMargins() {
    return ebitdaMargins;
  }

  public void setEbitdaMargins(YahooField ebitdaMargins) {
    this.ebitdaMargins = ebitdaMargins;
  }

  public YahooField getOperatingMargins() {
    return operatingMargins;
  }

  public void setOperatingMargins(YahooField operatingMargins) {
    this.operatingMargins = operatingMargins;
  }

  public YahooField getProfitMargins() {
    return profitMargins;
  }

  public void setProfitMargins(YahooField profitMargins) {
    this.profitMargins = profitMargins;
  }

  public YahooLongFormatField getNumberOfAnalystOpinions() {
    return numberOfAnalystOpinions;
  }

  public void setNumberOfAnalystOpinions(YahooLongFormatField numberOfAnalystOpinions) {
    this.numberOfAnalystOpinions = numberOfAnalystOpinions;
  }

  public YahooLongFormatField getTotalCash() {
    return totalCash;
  }

  public void setTotalCash(YahooLongFormatField totalCash) {
    this.totalCash = totalCash;
  }

  public YahooLongFormatField getEbitda() {
    return ebitda;
  }

  public void setEbitda(YahooLongFormatField ebitda) {
    this.ebitda = ebitda;
  }

  public YahooLongFormatField getTotalDebt() {
    return totalDebt;
  }

  public void setTotalDebt(YahooLongFormatField totalDebt) {
    this.totalDebt = totalDebt;
  }

  public YahooLongFormatField getTotalRevenue() {
    return totalRevenue;
  }

  public void setTotalRevenue(YahooLongFormatField totalRevenue) {
    this.totalRevenue = totalRevenue;
  }

  public YahooLongFormatField getDebtToEquity() {
    return debtToEquity;
  }

  public void setDebtToEquity(YahooLongFormatField debtToEquity) {
    this.debtToEquity = debtToEquity;
  }

  public YahooLongFormatField getGrossProfits() {
    return grossProfits;
  }

  public void setGrossProfits(YahooLongFormatField grossProfits) {
    this.grossProfits = grossProfits;
  }

  public YahooLongFormatField getFreeCashflow() {
    return freeCashflow;
  }

  public void setFreeCashflow(YahooLongFormatField freeCashflow) {
    this.freeCashflow = freeCashflow;
  }

  public YahooLongFormatField getOperatingCashflow() {
    return operatingCashflow;
  }

  public void setOperatingCashflow(YahooLongFormatField operatingCashflow) {
    this.operatingCashflow = operatingCashflow;
  }
}