package es.yahoousefulearnings.entities.option;

import com.fasterxml.jackson.annotation.JsonProperty;
import es.yahoousefulearnings.annotation.Entity;
import es.yahoousefulearnings.engine.Field;
import es.yahoousefulearnings.engine.LongFormatField;

/**
 * Generated by: "https://query1.finance.yahoo.com/v10/finance/quoteSummary/OPTION_SYMBOL?modules=price"
 * key to find in jackson: price
 *
 * @author Yago Rodríguez
 */
@Entity(getName = "Price")
public class Price extends OptionData {
  @JsonProperty("exchange")
  private String exchange; // "OPR",
  @JsonProperty("exchangeName")
  private String exchangeName; // "OPR",
  @JsonProperty("marketState")
  private String marketState; // "REGULAR",
  @JsonProperty("quoteType")
  private String quoteType; // "OPTION",
  @JsonProperty("symbol")
  private String symbol; // "AAPL160812C00070000",
  @JsonProperty("underlyingSymbol")
  private String underlyingSymbol; // "AAPL",
  @JsonProperty("currency")
  private String currency; // "USD",
  @JsonProperty("currencySymbol")
  private String currencySymbol; // "$"

  @JsonProperty("regularMarketChangePercent")
  private Field regularMarketChangePercent;
  @JsonProperty("regularMarketChange")
  private Field regularMarketChange;
  @JsonProperty("regularMarketTime")
  private Field regularMarketTime; // 1470439901,
  @JsonProperty("regularMarketPrice")
  private Field regularMarketPrice;
  @JsonProperty("regularMarketDayHigh")
  private Field regularMarketDayHigh;
  @JsonProperty("regularMarketDayLow")
  private Field regularMarketDayLow;
  @JsonProperty("regularMarketVolume")
  private LongFormatField regularMarketVolume;
  @JsonProperty("regularMarketPreviousClose")
  private Field regularMarketPreviousClose;
  @JsonProperty("regularMarketSource")
  private Field regularMarketSource; // "DELAYED",
  @JsonProperty("regularMarketOpen")
  private Field regularMarketOpen;
  @JsonProperty("strikePrice")
  private Field strikePrice;
  @JsonProperty("openInterest")
  private LongFormatField openInterest;
  @JsonProperty("expireDate")
  private Field expireDate;

  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public String getExchangeName() {
    return exchangeName;
  }

  public void setExchangeName(String exchangeName) {
    this.exchangeName = exchangeName;
  }

  public String getMarketState() {
    return marketState;
  }

  public void setMarketState(String marketState) {
    this.marketState = marketState;
  }

  public String getQuoteType() {
    return quoteType;
  }

  public void setQuoteType(String quoteType) {
    this.quoteType = quoteType;
  }

  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }

  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public String getCurrencySymbol() {
    return currencySymbol;
  }

  public void setCurrencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  public Field getRegularMarketChangePercent() {
    return regularMarketChangePercent;
  }

  public void setRegularMarketChangePercent(Field regularMarketChangePercent) {
    this.regularMarketChangePercent = regularMarketChangePercent;
  }

  public Field getRegularMarketChange() {
    return regularMarketChange;
  }

  public void setRegularMarketChange(Field regularMarketChange) {
    this.regularMarketChange = regularMarketChange;
  }

  public Field getRegularMarketTime() {
    return regularMarketTime;
  }

  public void setRegularMarketTime(Field regularMarketTime) {
    this.regularMarketTime = regularMarketTime;
  }

  public Field getRegularMarketPrice() {
    return regularMarketPrice;
  }

  public void setRegularMarketPrice(Field regularMarketPrice) {
    this.regularMarketPrice = regularMarketPrice;
  }

  public Field getRegularMarketDayHigh() {
    return regularMarketDayHigh;
  }

  public void setRegularMarketDayHigh(Field regularMarketDayHigh) {
    this.regularMarketDayHigh = regularMarketDayHigh;
  }

  public Field getRegularMarketDayLow() {
    return regularMarketDayLow;
  }

  public void setRegularMarketDayLow(Field regularMarketDayLow) {
    this.regularMarketDayLow = regularMarketDayLow;
  }

  public LongFormatField getRegularMarketVolume() {
    return regularMarketVolume;
  }

  public void setRegularMarketVolume(LongFormatField regularMarketVolume) {
    this.regularMarketVolume = regularMarketVolume;
  }

  public Field getRegularMarketPreviousClose() {
    return regularMarketPreviousClose;
  }

  public void setRegularMarketPreviousClose(Field regularMarketPreviousClose) {
    this.regularMarketPreviousClose = regularMarketPreviousClose;
  }

  public Field getRegularMarketSource() {
    return regularMarketSource;
  }

  public void setRegularMarketSource(Field regularMarketSource) {
    this.regularMarketSource = regularMarketSource;
  }

  public Field getRegularMarketOpen() {
    return regularMarketOpen;
  }

  public void setRegularMarketOpen(Field regularMarketOpen) {
    this.regularMarketOpen = regularMarketOpen;
  }

  public Field getStrikePrice() {
    return strikePrice;
  }

  public void setStrikePrice(Field strikePrice) {
    this.strikePrice = strikePrice;
  }

  public LongFormatField getOpenInterest() {
    return openInterest;
  }

  public void setOpenInterest(LongFormatField openInterest) {
    this.openInterest = openInterest;
  }

  public Field getExpireDate() {
    return expireDate;
  }

  public void setExpireDate(Field expireDate) {
    this.expireDate = expireDate;
  }
}
