package es.yahoousefulearnings.entities.option;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import es.yahoousefulearnings.engine.Field;
import es.yahoousefulearnings.engine.LongFormatField;

/**
 * Generated by: "https://query1.finance.yahoo.com/v10/finance/quoteSummary/OPTION_SYMBOL?modules=summaryDetail"
 * key to find in jackson: summaryDetail
 *
 * @author Yago Rodríguez
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SummaryProfile {
  @JsonProperty("previousClose")
  private Field previousClose;
  @JsonProperty("open")
  private Field open;
  @JsonProperty("dayLow")
  private Field dayLow;
  @JsonProperty("dayHigh")
  private Field dayHigh;
  @JsonProperty("regularMarketPreviousClose")
  private Field regularMarketPreviousClose;
  @JsonProperty("regularMarketOpen")
  private Field regularMarketOpen;
  @JsonProperty("regularMarketDayLow")
  private Field regularMarketDayLow;
  @JsonProperty("regularMarketDayHigh")
  private Field regularMarketDayHigh;
  @JsonProperty("bid")
  private Field bid;
  @JsonProperty("ask")
  private Field ask;
  @JsonProperty("expireDate")
  private Field expireDate;
  @JsonProperty("strikePrice")
  private Field strikePrice;
  @JsonProperty("fiftyTwoWeekLow")
  private Field fiftyTwoWeekLow;
  @JsonProperty("fiftyTwoWeekHigh")
  private Field fiftyTwoWeekHigh;
  @JsonProperty("openInterest")
  private LongFormatField openInterest;
  @JsonProperty("volume")
  private LongFormatField volume;
  @JsonProperty("regularMarketVolume")
  private LongFormatField regularMarketVolume;
}
